spring:
  application:
    name: mybatis-master-slave
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      jdbc-url: jdbc:mysql://localhost:3306/test2?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080

logging:
  level:
    com.yunus.mapper: debug